variable "rg_name" {}
variable "rg_location" {}
variable "costcenter" {}
variable "env" {}
variable "vnet_cidr" {}
variable "vnet_cidr_webservers" {}
variable "vnet_cidr_appservers" {}
variable "vnet_cidr_dbservers" {}
variable "kv_name" {}
variable "AzureFirewallSubnet" {}
